version: "3.8"

services:
  app:
    build:
      context: .               # Build from the root directory (to include all files)
      dockerfile: Dockerfile    # Use the Dockerfile at the root of the project
    ports:
      - "3000:3000"            # Map container port 3000 to local port 3000
    env_file:
      - ./pdf-quiz-chatbot/.env
      - ./pdf-quiz-chatbot/.env.local
    volumes:
      - ./pdf-quiz-chatbot:/app  # Mount the pdf-quiz-chatbot folder to /app inside the container
      - ./docker:/docker         # Mount the docker folder to access startup.sh
    working_dir: /app
    command: /docker/startup.sh  # Correct path to startup.sh script inside the container
