# docker-compose.yml

version: "3.8"

services:
  app:
    image: nextjs-app-dev  # Use the pre-built image
    ports:
      - "3000:3000"  # Map container port 3000 to local port 3000
    environment:
      # Load environment variables from the .env file in the same directory
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      # Add additional variables as needed
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    working_dir: /app
    command: npm run dev  # Start the development server
